DATASET:
  NAME: 'Indiana'
  ROOT: 'E:/zzy/GAN/data/Indiana'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'


DATALOADER:
  BATCH_SIZE: 64
  NUM_WORKERS: 0
  ITERATION: 658

MODEL:
  NAME: 'dsn_inn_nodis'
  BACKBONE: 'revnet38'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'cbst'
    - 'orthogonal'
    - 'l2dis'
  WEIGHTS:
    - 1.0
    - 1.0
    - 0.5
    - 0.5
  THRESHOLD: 0.7

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 20
