DATASET:
  NAME: 'ShangHang'
  ROOT: 'E:/zzy/GAN/data/ShanghaiHangzhou'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'

DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 1060

MODEL:
  NAME: 's4dl_ts'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'mmd'
    - 'orthogonal'
    - 'softmax+ce'
  WEIGHTS:
    - 0.8
    - 1.0
    - 0.1
    - 0.2
  KERNEL_NUM: 5

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001
  WEIGHT_DECAY: 0.0005

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 10

HYPERPARAMS:
  - 0.1
  - 1.0
  - 2.5
  - 0.18