DATASET:
  NAME: 'ShangHang'
  ROOT: 'E:/zzy/GAN/data/ShanghaiHangzhou'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'


DATALOADER:
  BATCH_SIZE: 128
  NUM_WORKERS: 0
  ITERATION: 1060

MODEL:
  NAME: 'dranet'
  BACKBONE: 'fe'

CRITERION:
  ITEMS:
    - 'softmax+ce' # cls_loss
    - 'softmax+ce' # dis_loss
    - 'l1dis' # Consistency_loss
    - 'l2dis' # Content_loss
    - 'l2dis' # Style_Loss
    - 'softmax+ce' # G_loss
    - 'l1dis' # Recon_loss
  WEIGHTS:
    - 1.0
    - 0.5
    - 1.0
    - 1.0
    - 1.0
    - 0.5
    - 1.0

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 5
