DATASET:
  NAME: 'Houston'
  ROOT: 'E:/zzy/GAN/data/Houston'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'

DATALOADER:
  BATCH_SIZE: 64
  NUM_WORKERS: 0
  ITERATION: 40

MODEL:
  NAME: 's4dl_ts'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'cbst'
    - 'orthogonal'
    - 'softmax+ce'
  WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 0.5
  THRESHOLD: 0.7

OPTIMIZER:
  NAME: 'adam'
  LR: 0.003
  WEIGHT_DECAY: 0.0005

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.5
  PATIENCE: 3

EPOCHS: 30

HYPERPARAMS:
  - 0.05
  - 1.0
  - 2.5
  - 0.0645