CRITERION:
  ITEMS1:
  - softmax+ce
  - softmax+ce
  - softmax+ce
  ITEMS2:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  ITEMS3:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  ITEMS4:
  - softmax+ce
  KERNEL_NUM: 1
  WEIGHTS1:
  - 1.0
  - 1.0
  - 1.0
  WEIGHTS2:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  WEIGHTS3:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  WEIGHTS4:
  - 1.0
DATALOADER:
  BATCH_SIZE: 64
  NUM_WORKERS: 0
DATASET:
  AUGMENT:
    RATIO: 21
    TRANS: ''
  NAME: PREPROCESSED_Houston
  PATCH:
    HEIGHT: 0
    PAD_MODE: ''
    WIDTH: 0
  ROOT: E:/zzy/GAN/HSI_domain_adaptation/dataset/houston_preprocessed
EPOCHFE: 4
EPOCHS: 10
MODEL:
  NAME: dann
OPTIMIZER:
  LR1: 0.001
  LR2: 0.0
  LR3: 0.0
  MOMENTUM: 0.0
  NAME1: adam
  NAME2: ''
  NAME3: ''
  WEIGHT_DECAY: 0.0
SCHEDULER:
  FACTOR: 0.1
  GAMMA: 0.0
  MODE: min
  NAME: plateau
  PATIENCE: 2
