DATASET:
  NAME: 'HyRANK'
  ROOT: 'E:/zzy/GAN/data/HyRANK'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'

DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 0
  ITERATION: 626

MODEL:
  NAME: 's4dl_ts'
  BACKBONE: 'fe_rev'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'mmd'
    - 'orthogonal'
    - 'softmax+ce'
  WEIGHTS:
    - 1.0
    - 1.0
    - 0.1
    - 0.5
  KERNEL_NUM: 5

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 20

HYPERPARAMS:
  - 0.1
  - 1.0
  - 2.5
  - 0.095