DATASET:
    NAME: 'PREPROCESSED_ShangHang'
    ROOT: 'E:/zzy/GAN/HSI_domain_adaptation/dataset/shanghaihangzhou_preprocessed'
    PATCH:
      HEIGHT: 27
      WIDTH: 27
      PAD_MODE: 'symmetric'
    AUGMENT:
      RATIO: 1
      TRANS: ''

DATALOADER:
    BATCH_SIZE: 256
    NUM_WORKERS: 0

MODEL:
    NAME: 'dann'

CRITERION:
    ITEMS1:
      - 'softmax+ce'
      - 'softmax+ce'
      - 'softmax+ce'
    WEIGHTS1:
      - 1.0
      - 1.0
      - 1.0
    ITEMS4:
      - 'softmax+ce'
    WEIGHTS4:
      - 1.0
    KERNEL_NUM: 1

OPTIMIZER:
    NAME1: 'adam'
    LR1: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 10

EPOCHFE: 1
