DATASET:
    NAME: 'PREPROCESSED_ShangHang'
    ROOT: 'E:/zzy/GAN/HSI_domain_adaptation/dataset/shanghaihangzhou_preprocessed'
    PATCH:
      HEIGHT: 27
      WIDTH: 27
      PAD_MODE: 'symmetric'
    AUGMENT:
      RATIO: 3
      TRANS: ''

DATALOADER:
    BATCH_SIZE: 128
    NUM_WORKERS: 0

MODEL:
    NAME: 'pixelda-caps-3d'

CRITERION:
    ITEMS1:
      - 'margin'
      - 'margin'
    WEIGHTS1:
      - 1.0
      - 1.0
    ITEMS2:
      - 'softmax+ce'
      - 'softmax+ce'
    WEIGHTS2:
      - 1.0
      - 1.0
    ITEMS3:
      - 'softmax+ce'
      - 'class_weight_ce'
    WEIGHTS3:
      - 1.0
      - 1.0
    ITEMS4:
      - 'softmax+ce'
    WEIGHTS4:
      - 1.0
    KERNEL_NUM: 1

OPTIMIZER:
    NAME1: 'adam'
    LR1: 0.003
    NAME2: 'adam'
    LR2: 0.001
    NAME3: 'adam'
    LR3: 0.0001
    MOMENTUM: 0.9

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 10

EPOCH_RESAMPLE: 1

